#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#MISE description="Show CLI version"
set -euo pipefail

GIT_SHORT_SHA=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
VERSION="${VERSION:-dev-$GIT_SHORT_SHA}"
echo "$VERSION"
