// SPDX-License-Identifier: Apache-2.0
package init

import (
	"strings"
	"testing"

	initpkg "github.com/Work-Fort/Anvil/pkg/init"
)

func TestX86ConfigTemplate_NonEmpty(t *testing.T) {
	if initpkg.X86ConfigTemplate == "" {
		t.Error("initpkg.X86ConfigTemplate should not be empty")
	}
}

func TestAarch64ConfigTemplate_NonEmpty(t *testing.T) {
	if initpkg.Aarch64ConfigTemplate == "" {
		t.Error("initpkg.Aarch64ConfigTemplate should not be empty")
	}
}

func TestX86ConfigTemplate_ContainsHeader(t *testing.T) {
	if !strings.Contains(initpkg.X86ConfigTemplate, "Generated by anvil init") {
		t.Error("initpkg.X86ConfigTemplate should contain 'Generated by anvil init'")
	}
}

func TestAarch64ConfigTemplate_ContainsHeader(t *testing.T) {
	if !strings.Contains(initpkg.Aarch64ConfigTemplate, "Generated by anvil init") {
		t.Error("initpkg.Aarch64ConfigTemplate should contain 'Generated by anvil init'")
	}
}

func TestX86ConfigTemplate_ContainsTODO(t *testing.T) {
	if !strings.Contains(initpkg.X86ConfigTemplate, "TODO") {
		t.Error("initpkg.X86ConfigTemplate should contain TODO comment")
	}
}

func TestAarch64ConfigTemplate_ContainsTODO(t *testing.T) {
	if !strings.Contains(initpkg.Aarch64ConfigTemplate, "TODO") {
		t.Error("initpkg.Aarch64ConfigTemplate should contain TODO comment")
	}
}

func TestTemplates_AreDifferent(t *testing.T) {
	if initpkg.X86ConfigTemplate == initpkg.Aarch64ConfigTemplate {
		t.Error("initpkg.X86ConfigTemplate and initpkg.Aarch64ConfigTemplate should be different (architecture-specific)")
	}
}

func TestX86ConfigTemplate_ContainsArchitectureReference(t *testing.T) {
	template := strings.ToLower(initpkg.X86ConfigTemplate)
	if !strings.Contains(template, "x86_64") && !strings.Contains(template, "x86-64") {
		t.Error("initpkg.X86ConfigTemplate should reference x86_64 architecture")
	}
}

func TestAarch64ConfigTemplate_ContainsArchitectureReference(t *testing.T) {
	template := strings.ToLower(initpkg.Aarch64ConfigTemplate)
	if !strings.Contains(template, "aarch64") && !strings.Contains(template, "arm64") {
		t.Error("initpkg.Aarch64ConfigTemplate should reference aarch64 architecture")
	}
}

func TestGitignoreTemplate_NonEmpty(t *testing.T) {
	if initpkg.GitignoreTemplate == "" {
		t.Error("initpkg.GitignoreTemplate should not be empty")
	}
}

func TestGitignoreTemplate_ContainsBuildDir(t *testing.T) {
	if !strings.Contains(initpkg.GitignoreTemplate, "build/") {
		t.Error("initpkg.GitignoreTemplate should contain 'build/'")
	}
}

func TestRepoConfigTemplate_NonEmpty(t *testing.T) {
	if initpkg.RepoConfigTemplate == "" {
		t.Error("initpkg.RepoConfigTemplate should not be empty")
	}
}

func TestRepoConfigTemplate_ContainsTemplatePlaceholders(t *testing.T) {
	if !strings.Contains(initpkg.RepoConfigTemplate, "{{.KeyName}}") {
		t.Error("initpkg.RepoConfigTemplate should contain template placeholder '{{.KeyName}}'")
	}
}
