// SPDX-License-Identifier: Apache-2.0
package init

// X86ConfigTemplate is the minimal kernel config template for x86_64 architecture
const X86ConfigTemplate = `# Generated by anvil init
# Minimal Firecracker Kernel Config - x86_64

# This is a minimal configuration template to get you started.
# You should customize this file with the specific CONFIG_* options
# needed for your use case (networking, filesystems, devices, etc.).
#
# TODO: Update this template when official configuration documentation
# becomes available at https://github.com/Work-Fort/Anvil

# Add your CONFIG_* options below:

`

// Aarch64ConfigTemplate is the minimal kernel config template for aarch64 architecture
const Aarch64ConfigTemplate = `# Generated by anvil init
# Minimal Firecracker Kernel Config - aarch64

# This is a minimal configuration template to get you started.
# You should customize this file with the specific CONFIG_* options
# needed for your use case (networking, filesystems, devices, etc.).
#
# TODO: Update this template when official configuration documentation
# becomes available at https://github.com/Work-Fort/Anvil

# Add your CONFIG_* options below:

`

// GitignoreTemplate is the .gitignore file template
const GitignoreTemplate = `# Kernel build artifacts
build/
vmlinux*
Image*
*.tar.xz
*.tar.gz

# Local archives
{{.ArchiveLocation}}/
`

// RepoConfigTemplate is the anvil.yaml template
const RepoConfigTemplate = `# Generated by anvil init
kernels:
  config:
    x86_64: configs/kernel-x86_64.config
    aarch64: configs/kernel-aarch64.config
  archive:
    location: {{.ArchiveLocation}}

signing:
  key:
    name: "{{.KeyName}}"
    email: "{{.KeyEmail}}"
    expiry: "{{.KeyExpiry}}"
    format: "{{.KeyFormat}}"
    location: keys
  history:
    location: keys/history
    format: "{{.HistoryFormat}}"
`
